apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 75611bf9-4221-4c48-a98d-0912ef64016e
    workflow_id: a9bffe77-0376-4f9c-986e-baa6fa49bbf2
  name: myapp-pod-delete
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - arguments: {}
    inputs: {}
    metadata: {}
    name: custom-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: pod-delete
        template: pod-delete
    - - arguments: {}
        name: revert-chaos
        template: revert-chaos
    - - arguments: {}
        name: echo-chaos
        template: echo-chaos
  - arguments: {}
    container:
      args:
      - kubectl apply -f https://github.com/litmuschaos/chaos-charts/raw/master/charts/generic/pod-delete/experiment.yaml -n {{workflow.parameters.adminModeNamespace}} | sleep 30
      command:
      - sh
      - -c
      image: lachlanevenson/k8s-kubectl
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - arguments: {}
    container:
      args:
      - -file=/tmp/chaosengine-pod-delete.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-delete
        path: /tmp/chaosengine-pod-delete.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              name: pod-delete
              namespace: "{{workflow.parameters.adminModeNamespace}}"
            spec:
              appinfo:
                appns: litmus
                applabel: app=myapp
                appkind: deployment
              annotationCheck: "false"
              engineState: active
              chaosServiceAccount: litmus-admin
              monitoring: false
              jobCleanUpPolicy: delete
              experiments:
                - name: pod-delete
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "20"
                        - name: CHAOS_INTERVAL
                          value: "10"
                        - name: FORCE
                          value: "false"
    metadata:
      labels:
        weight: "10"
    name: pod-delete
    outputs: {}
  - arguments: {}
    container:
      args:
      - kubectl delete chaosengines --all -n {{workflow.parameters.adminModeNamespace}}
      command:
      - sh
      - -c
      image: lachlanevenson/k8s-kubectl
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: revert-chaos
    outputs: {}
  - arguments: {}
    container:
      args:
      - echo "chaos"
      command:
      - bash
      - -c
      image: bash
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: echo-chaos
    outputs: {}
status:
  finishedAt: null
  startedAt: null
