apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: test-app
  labels:
    tenant: test
spec:
  generators:
  - list:
      elements:
      - server: https://kubernetes.default.svc
        namespace: test-app
        cluster: incluster
  template:
    metadata:
      name: '{{cluster}}-logging'
      labels:
        tenant: pac
    spec:
      project: default      
      sources:
        - chart: sealed-secrets
          repoURL: https://bitnami-labs.github.io/sealed-secrets
          targetRevision: 1.16.1
          helm:
            releaseName: sealed-secrets
        - repoURL: https://github.com/argoproj/argocd-example-apps.git
          targetRevision: HEAD
          path: kustomize-guestbook
      destination:
        server: '{{server}}'
        namespace: '{{namespace}}'
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        automated:
          selfHeal: true
