apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
spec:
  generators:
  - git:
    repoURL: git@github.com:argoproj/argocd-example-apps.git
    revision: HEAD
    files:
    - path: ./**/**/kustomization.yaml
  template:
    metadata:
      name: '{{path}}-guestbook'
    spec:
      project: "default"
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps/
        targetRevision: HEAD
        path: '{{path}}'
      destination:
        name: cluster-test
        namespace: default
