apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: f008df53-bafe-4a3d-8fa9-50ce73eb3ebb
    workflow_id: acc98573-7b6d-4ef3-b33d-4966e9da5902
  name: custom-chaos-workflow-1616598891
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: argowf-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - arguments: {}
    inputs: {}
    metadata: {}
    name: argowf-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-chaos-experiments
        template: install-chaos-experiments
    - - arguments: {}
        name: node-cpu-hog
        template: node-cpu-hog
    - - arguments: {}
        name: revert-kube-proxy-chaos
        template: revert-kube-proxy-chaos
  - arguments: {}
    container:
      args:
      - kubectl apply -f https://hub.litmuschaos.io/api/chaos/1.12.0?file=charts/generic/experiments.yaml -n {{workflow.parameters.adminModeNamespace}} | sleep 30
      command:
      - sh
      - -c
      image: alpine/k8s:1.18.2
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: install-chaos-experiments
    outputs: {}
  - arguments: {}
    container:
      args:
      - -file=/tmp/chaosengine-node-cpu-hog.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: node-cpu-hog
        path: /tmp/chaosengine-node-cpu-hog.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              name: kube-proxy-node-cpu-hog-1616597745
              namespace: "{{workflow.parameters.adminModeNamespace}}"
            spec:
              appinfo:
                appns: kube-system
                applabel: k8s-app=kube-proxy
                appkind: daemonset
              jobCleanUpPolicy: delete
              monitoring: false
              annotationCheck: "false"
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: node-cpu-hog
                  spec:
                    components:
                      env:
                        - name: NODE_CPU_CORE
                          value: "1"
                        - name: TOTAL_CHAOS_DURATION
                          value: "20"
    metadata:
      labels:
        weight: "10"
    name: node-cpu-hog
    outputs: {}
  - arguments: {}
    container:
      args:
      - -file=/tmp/chaosengine-pod-memory-hog.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-memory-hog
        path: /tmp/chaosengine-pod-memory-hog.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              name: kube-proxy-pod-memory-hog-chaos-1616597745
              namespace: "{{workflow.parameters.adminModeNamespace}}"
            spec:
              appinfo:
                appns: kube-system
                applabel: k8s-app=kube-proxy
                appkind: daemonset
              jobCleanUpPolicy: retain
              monitoring: false
              annotationCheck: "false"
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: pod-memory-hog
                  spec:
                    components:
                      experimentImage: litmuschaos/go-runner:ci
                      env:
                        - name: TARGET_CONTAINER
                          value: kube-proxy
                        - name: MEMORY_CONSUMPTION
                          value: "500"
                        - name: TOTAL_CHAOS_DURATION
                          value: "60"
                        - name: CHAOS_KILL_COMMAND
                          value: kill $(find /proc -name exe -lname '*/dd' 2>&1 | grep -v 'Permission
                            denied' | awk -F/ '{print $(NF-1)}' |  head -n 1)
    metadata:
      labels:
        weight: "10"
    name: pod-memory-hog
    outputs: {}
  - arguments: {}
    container:
      args:
      - -file=/tmp/chaosengine-pod-cpu-hog.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-cpu-hog
        path: /tmp/chaosengine-pod-cpu-hog.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              name: kube-proxy-pod-cpu-hog-chaos-1616597745
              namespace: "{{workflow.parameters.adminModeNamespace}}"
            spec:
              appinfo:
                appns: kube-system
                applabel: k8s-app=kube-proxy
                appkind: daemonset
              jobCleanUpPolicy: retain
              monitoring: false
              annotationCheck: "false"
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: pod-cpu-hog
                  spec:
                    components:
                      experimentImage: litmuschaos/go-runner:ci
                      env:
                        - name: TARGET_CONTAINER
                          value: kube-proxy
                        - name: CPU_CORES
                          value: "1"
                        - name: TOTAL_CHAOS_DURATION
                          value: "60"
                        - name: CHAOS_KILL_COMMAND
                          value: kill $(find /proc -name exe -lname '*/md5sum' 2>&1 | grep -v 'Permission
                            denied' | awk -F/ '{print $(NF-1)}' |  head -n 1)
    metadata:
      labels:
        weight: "10"
    name: pod-cpu-hog
    outputs: {}
  - arguments: {}
    container:
      args:
      - -file=/tmp/chaosengine-node-memory-hog.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: node-memory-hog
        path: /tmp/chaosengine-node-memory-hog.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              name: kube-proxy-node-memory-hog-chaos-1616597745
              namespace: "{{workflow.parameters.adminModeNamespace}}"
            spec:
              appinfo:
                appns: kube-system
                applabel: k8s-app=kube-proxy
                appkind: daemonset
              jobCleanUpPolicy: retain
              monitoring: false
              annotationCheck: "false"
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: node-memory-hog
                  spec:
                    components:
                      env:
                        - name: MEMORY_PERCENTAGE
                          value: "50"
                        - name: TOTAL_CHAOS_DURATION
                          value: "60"
    metadata:
      labels:
        weight: "10"
    name: node-memory-hog
    outputs: {}
  - arguments: {}
    container:
      args:
      - -file=/tmp/chaosengine-pod-delete.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: pod-delete
        path: /tmp/chaosengine-pod-delete.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              name: kube-proxy-pod-delete-chaos-1616597745
              namespace: "{{workflow.parameters.adminModeNamespace}}"
            spec:
              appinfo:
                appns: kube-system
                applabel: k8s-app=kube-proxy
                appkind: daemonset
              jobCleanUpPolicy: retain
              monitoring: false
              annotationCheck: "false"
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: pod-delete
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "60"
                        - name: CHAOS_INTERVAL
                          value: "10"
                        - name: FORCE
                          value: "false"
    metadata:
      labels:
        weight: "10"
    name: pod-delete
    outputs: {}
  - arguments: {}
    container:
      args:
      - kubectl delete chaosengine kube-proxy-node-cpu-hog-1616597745  -n {{workflow.parameters.adminModeNamespace}}
      command:
      - sh
      - -c
      image: alpine/k8s:1.18.2
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: revert-kube-proxy-chaos
    outputs: {}
status:
  finishedAt: null
  startedAt: null
