apiVersion: batch/v1
kind: Job
metadata:
  name: hello
  annotations:
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/sync-wave: "-1"
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    metadata:
      name: hello-world-job
    spec:
      containers:
      - name: hello-world
        image: centos:6
        command:
         - "bin/bash"
         - "-c"
         - "echo hello world"
      restartPolicy: Never
