apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  labels:
    cluster_id: b87bf3bd-b770-4c33-bbde-5306fa32f324
    workflow_id: 59fcf3c5-6ce0-4ae2-9354-22355037d5b5
  name: custom-chaos-workflow-1610955385
  namespace: kubera
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: kubera
  entrypoint: custom-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - name: custom-chaos
    steps:
    - - name: install-chaos-experiments
        template: install-chaos-experiments
    - - name: pod-delete
        template: pod-delete
    - - name: revert-chaos
        template: revert-chaos
  - container:
      args:
      - kubectl apply -f https://github.com/mayadata-io/kubera-chaos-charts/raw/master/charts/generic/pod-delete/experiment.yaml -n {{workflow.parameters.adminModeNamespace}} | sleep 30
      command:
      - sh
      - -c
      image: lachlanevenson/k8s-kubectl
    name: install-chaos-experiments
  - container:
      args:
      - -file=/tmp/chaosengine-pod-delete.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:latest
    inputs:
      artifacts:
      - name: pod-delete
        path: /tmp/chaosengine-pod-delete.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              name: pod-delete
              namespace: "{{workflow.parameters.adminModeNamespace}}"
            spec:
              appinfo:
                appns: kube-system
                applabel: k8s-app=kube-proxy
                appkind: daemonset
              annotationCheck: "false"
              engineState: active
              auxiliaryAppInfo: ""
              chaosServiceAccount: litmus-admin
              monitoring: false
              jobCleanUpPolicy: delete
              experiments:
                - name: pod-delete
                  spec:
                    components:
                      env:
                        - name: TOTAL_CHAOS_DURATION
                          value: "30"
                        - name: CHAOS_INTERVAL
                          value: "10"
                        - name: FORCE
                          value: "false"
                        - name: jobCleanUpPolicy
                          value: retain
    name: pod-delete
  - container:
      args:
      - kubectl delete chaosengines --all -n {{workflow.parameters.adminModeNamespace}}
      command:
      - sh
      - -c
      image: lachlanevenson/k8s-kubectl
    name: revert-chaos
