apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  creationTimestamp: null
  labels:
    cluster_id: 17c88bd4-c318-45c3-86ff-ca6a6cc2cdca
    workflow_id: e18de77c-f500-4907-b163-f590a4a3046b
  name: argowf-chaos-node-cpu-hog-1614848875
  namespace: litmus
spec:
  arguments:
    parameters:
    - name: adminModeNamespace
      value: litmus
  entrypoint: argowf-chaos
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: argo-chaos
  templates:
  - arguments: {}
    inputs: {}
    metadata: {}
    name: argowf-chaos
    outputs: {}
    steps:
    - - arguments: {}
        name: install-experiment
        template: install-experiment
    - - arguments: {}
        name: run-chaos
        template: run-chaos
    - - arguments: {}
        name: revert-chaos
        template: revert-chaos
  - arguments: {}
    container:
      args:
      - kubectl apply -f /tmp/node-cpu-hog.yaml -n {{workflow.parameters.adminModeNamespace}}
      command:
      - sh
      - -c
      image: lachlanevenson/k8s-kubectl
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: install-experiment
        path: /tmp/node-cpu-hog.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            description:
              message: |
                Give a cpu spike on a node belonging to a deployment
            kind: ChaosExperiment
            metadata:
              name: node-cpu-hog
            spec:
              definition:
                scope: Cluster
                permissions:
                  - apiGroups:
                      - ""
                      - batch
                      - apps
                      - litmuschaos.io
                    resources:
                      - jobs
                      - pods
                      - pods/log
                      - events
                      - chaosengines
                      - chaosexperiments
                      - chaosresults
                    verbs:
                      - create
                      - list
                      - get
                      - patch
                      - update
                      - delete
                  - apiGroups:
                      - ""
                    resources:
                      - nodes
                    verbs:
                      - get
                      - list
                image: litmuschaos/go-runner:latest
                imagePullPolicy: Always
                args:
                  - -c
                  - ./experiments -name node-cpu-hog
                command:
                  - /bin/bash
                env:
                  - name: TOTAL_CHAOS_DURATION
                    value: "60"
                  - name: RAMP_TIME
                    value: ""
                  - name: NODE_CPU_CORE
                    value: ""
                  - name: LIB
                    value: litmus
                  - name: LIB_IMAGE
                    value: litmuschaos/go-runner:latest
                labels:
                  name: node-cpu-hog
    metadata: {}
    name: install-experiment
    outputs: {}
  - arguments: {}
    container:
      args:
      - -file=/tmp/chaosengine.yaml
      - -saveName=/tmp/engine-name
      image: litmuschaos/litmus-checker:latest
      name: ""
      resources: {}
    inputs:
      artifacts:
      - name: run-chaos
        path: /tmp/chaosengine.yaml
        raw:
          data: |
            apiVersion: litmuschaos.io/v1alpha1
            kind: ChaosEngine
            metadata:
              name: kube-proxy-node-cpu-hog-chaos-1614848876
              namespace: "{{workflow.parameters.adminModeNamespace}}"
            spec:
              appinfo:
                appns: kube-system
                applabel: k8s-app=kube-proxy
                appkind: daemonset
              jobCleanUpPolicy: retain
              monitoring: false
              annotationCheck: "false"
              engineState: active
              chaosServiceAccount: litmus-admin
              experiments:
                - name: node-cpu-hog
                  spec:
                    components:
                      env:
                        - name: NODE_CPU_CORE
                          value: "1"
                        - name: TOTAL_CHAOS_DURATION
                          value: "60"
    metadata:
      labels:
        weight: "10"
    name: run-chaos
    outputs: {}
  - arguments: {}
    container:
      args:
      - kubectl delete chaosengine kube-proxy-node-cpu-hog-chaos-1614848876  -n {{workflow.parameters.adminModeNamespace}}
      command:
      - sh
      - -c
      image: lachlanevenson/k8s-kubectl
      name: ""
      resources: {}
    inputs: {}
    metadata: {}
    name: revert-chaos
    outputs: {}
status:
  finishedAt: null
  startedAt: null
