apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    litmuschaos.io/gitops: "true"
    litmuschaos.io/workflow: 7efc2cd9-7ff8-44b8-95aa-8e832a933ef9
  labels:
    app: myapp
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - image: gdsoumya/myapp:2.0
        imagePullPolicy: Always
        name: myapp
        ports:
          - containerPort: 80
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      targetPort: 80
      nodePort: 31000
  selector:
    app: myapp
