apiVersion: apps/v1
kind: Deployment
metadata:
   annotations:
    litmuschaos.io/gitops: "true"
    litmuschaos.io/workflow: ce4bbfd4-4205-45a7-9fcb-46a610fe3f98
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged:1.18
        imagePullPolicy: Always
        name: nginx
      restartPolicy: Always
