apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    litmuschaos.io/gitops: "true"
    litmuschaos.io/workflow: f14722d6-ac0b-4b08-be0a-4252afd0c818
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginxinc/nginx-unprivileged:1.19
        imagePullPolicy: Always
        name: nginx
      restartPolicy: Always
